### ISSUE TITLE
Center main content

### ISSUE THREAD

**Issue by martoio** [mkabobel/teacozy#2]
Try doing ``margin: 0 auto;`` to center the main content
https://github.com/mkabobel/teacozy/blob/fd417c755d1e5beb1b7d05ef5a7ffe3a6e7b1f88/Documents/DesignWork/Projects/TeaCozy/resources/css/style.css#L135

**Comment by mkabobel** [comment]
I was having trouble with this, so I'll try this out. Thanks!
