### ISSUE TITLE
Summary: Meets expectations

### ISSUE THREAD

**Issue by martoio** [mkabobel/teacozy#5]
Good job! Your code is clean, but try to implement the images in your repo next time so you don't end up with missing pieces in your submission. Another thing you could do is to just use the links that are given to you for the images (instead of downloading the images).

As a challenge, you can research and implement media queries to make your page responsive for different devices. You should be able to take a crack at this and make it good! Here are a couple resources to get you started: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries and https://css-tricks.com/snippets/css/media-queries-for-standard-devices/

Great job and keep up the good work!

**Comment by mkabobel** [comment]
Thank you!
